# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f0e11ebae9b52305e01d3d9f8b292a619dd1dad74cc851c411c7ecfc966d2750ddaa0533d6b464455a197297204b56c4f3fe14133aff2b8be473592d6438a2

test:
  secret_key_base: c5ecc4963d2b631d415d0dd8f18ba8e5b37e5795f90ae2ce922bb680e936914e7de7b021203a9539ec69fb9f9612c10f778a4207b3290c28fc9427a3176e2f2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
